-- Inventorium multi-venue, piece 2: ids unique PER VENUE.
--
-- Why: ids like ADMIN-1 or LX-0001 are generated by the app, so two venues will
-- eventually create the same id. With one global primary key the second venue
-- would collide with (or overwrite) the first venue's row. This makes every
-- primary key (venue_id, id) and re-points the links between tables the same way,
-- so a row can only ever be linked to rows in its own venue.
--
-- Needs Postgres 15+ (Supabase projects normally are). Safe to run more than once.
-- All one transaction: if anything fails, nothing is changed.
--
-- ORDER MATTERS: run this, then deploy the piece-2 code right away. The old code
-- looks rows up by id alone and the new code by (venue_id, id), so the site will
-- error for the minute or two between the two steps. Pick a quiet moment.
--
-- To undo: db/venues-ids-rollback.sql  (and redeploy the old code)

begin;

do $$
declare
  r record;
  t text;
  pk text;
begin
  if current_setting('server_version_num')::int < 150000 then
    raise exception 'This script needs Postgres 15 or newer (found %).', current_setting('server_version');
  end if;

  -- 1. Drop the old single-column links between tables.
  for r in
    select conrelid::regclass::text as tbl, conname
      from pg_constraint
     where contype = 'f'
       and conrelid  in ('public.items'::regclass, 'public.call_list'::regclass)
       and confrelid in ('public.employees'::regclass, 'public.shows'::regclass, 'public.show_roles'::regclass)
  loop
    execute format('alter table %s drop constraint %I', r.tbl, r.conname);
  end loop;

  -- 2. Primary keys: id  ->  (venue_id, id)
  foreach t in array array['employees', 'roles', 'locations', 'items', 'shows', 'show_roles', 'call_list', 'activity_log'] loop
    if to_regclass('public.' || t) is null then continue; end if;
    select conname into pk from pg_constraint
     where conrelid = ('public.' || t)::regclass and contype = 'p' and array_length(conkey, 1) = 1;
    if pk is not null then
      execute format('alter table public.%I drop constraint %I', t, pk);
      execute format('alter table public.%I add primary key (venue_id, id)', t);
    end if;
  end loop;

  -- 3. One call-list row per person per show, within a venue.
  for r in
    select conname from pg_constraint c
     where conrelid = 'public.call_list'::regclass and contype = 'u' and array_length(conkey, 1) = 2
       and (select array_agg(attname::text order by attname) from pg_attribute
             where attrelid = c.conrelid and attnum = any (c.conkey)) = array['emp_id', 'show_id']
  loop
    execute format('alter table public.call_list drop constraint %I', r.conname);
  end loop;
  if not exists (select 1 from pg_constraint where conname = 'call_list_venue_show_emp_key') then
    alter table public.call_list add constraint call_list_venue_show_emp_key unique (venue_id, show_id, emp_id);
  end if;

  -- 4. Links between tables now include the venue, so they can't cross venues.
  alter table public.items add constraint items_venue_holder_fkey
    foreign key (venue_id, holder) references public.employees (venue_id, id) on delete set null (holder);
  alter table public.call_list add constraint call_list_venue_show_fkey
    foreign key (venue_id, show_id) references public.shows (venue_id, id) on delete cascade;
  alter table public.call_list add constraint call_list_venue_emp_fkey
    foreign key (venue_id, emp_id) references public.employees (venue_id, id) on delete cascade;
  alter table public.call_list add constraint call_list_venue_showrole_fkey
    foreign key (venue_id, show_role_id) references public.show_roles (venue_id, id) on delete set null (show_role_id);
end $$;

commit;

-- ===== verify =====
-- Every data table should list its primary key as (venue_id, id); the three
-- link rows should say "venue_id, ..." too.
select conrelid::regclass as "table", contype as kind, pg_get_constraintdef(oid) as definition
  from pg_constraint
 where conrelid in ('public.employees'::regclass, 'public.roles'::regclass, 'public.locations'::regclass,
                    'public.items'::regclass, 'public.shows'::regclass, 'public.show_roles'::regclass,
                    'public.call_list'::regclass, 'public.activity_log'::regclass)
   and contype in ('p', 'f', 'u')
 order by conrelid::regclass::text, contype, conname;
